<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <NopCommerceRootDir>$(SolutionDir)NopCommerce\src</NopCommerceRootDir>

    <!-- Variables internas para los parámetros del script -->
    <ScriptArg2>SolutionDir)\\</ScriptArg2>
    <ScriptArg3>SolutionDir)NopCommerce\src\\</ScriptArg3>
    <ScriptArg4>*.csproj</ScriptArg4>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
  </ItemGroup>

  <Target Name="RunBeforeRestore" BeforeTargets="Restore;CollectPackageReferences"
    Condition="Exists('$(NopCommerceRootDir)')">

    <!-- Windows -->
    <Exec Condition="'$(OS)' == 'Windows_NT'"
      Command="xcopy /Y/E &quot;$(SolutionDir)CustomEcommerce\NopCommerce\Libraries\*&quot; &quot;$(NopCommerceRootDir)\Libraries\&quot;" />
    <Exec Condition="'$(OS)' == 'Windows_NT'"
      Command="xcopy /Y/E &quot;$(SolutionDir)CustomEcommerce\NopCommerce\Presentation\*&quot; &quot;$(NopCommerceRootDir)\Presentation\&quot;" />
    <Exec Condition="'$(OS)' == 'Windows_NT'"
      Command="xcopy /Y/E &quot;$(SolutionDir)CustomEcommerce\NopCommerce\Plugins\*&quot; &quot;$(NopCommerceRootDir)\Plugins\&quot;" />
    <Exec Condition="'$(OS)' == 'Windows_NT'"
      Command="xcopy /Y/E &quot;$(SolutionDir)CustomEcommerce\NopCommerce\Tests\*&quot; &quot;$(NopCommerceRootDir)\Tests\&quot;" />

    <!-- Linux/macOS -->
    <Exec Condition="'$(OS)' != 'Windows_NT'"
      Command="cp -r &quot;$(SolutionDir)CustomEcommerce/NopCommerce/Libraries/*&quot; &quot;$(NopCommerceRootDir)/Libraries/&quot;" />
    <Exec Condition="'$(OS)' != 'Windows_NT'"
      Command="cp -r &quot;$(SolutionDir)CustomEcommerce/NopCommerce/Presentation/*&quot; &quot;$(NopCommerceRootDir)/Presentation/&quot;" />

    <Exec Condition="'$(OS)' == 'Windows_NT'"
      Command="powershell -ExecutionPolicy Bypass -File &quot;$(SolutionDir)\BeforeBuild\Utils\Replacer.ps1&quot; &quot;$(NopCommerceRootDir)&quot; &quot;$(ScriptArg2)&quot; &quot;$(ScriptArg3)&quot; &quot;$(ScriptArg4)&quot;" />
    <Exec Condition="'$(OS)' != 'Windows_NT'"
      Command="bash &quot;$(SolutionDir)/BeforeBuild/Utils/Replacer.sh&quot; &quot;$(NopCommerceRootDir)&quot; &quot;$(ScriptArg2)&quot; &quot;$(ScriptArg3)&quot; &quot;$(ScriptArg4)&quot;" />
  </Target>
</Project>