<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' == '' ">0.0.1-local</Version>
    <Version Condition=" '$(BUILD_BUILDNUMBER)' != '' ">$(BUILD_BUILDNUMBER)</Version>
    <Copyright>Copyright © Kivio 2025</Copyright>
    <Company>Kivio</Company>
    <Authors>Kivio</Authors>
    <AssemblyName>ElectronicInvoice.SIIGO</AssemblyName>
    <RootNamespace>ElectronicInvoice.SIIGO</RootNamespace>
    <PluginDirectory>ElectronicInvoice.SIIGO</PluginDirectory>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>$(SolutionDir)NopCommerce\src\Presentation\Nop.Web\Plugins\ElectronicInvoice.SIIGO</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>$(SolutionDir)NopCommerce\src\Presentation\Nop.Web\Plugins\ElectronicInvoice.SIIGO</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)NopCommerce\src\Libraries\Nop.Core\Nop.Core.csproj" />
    <ProjectReference Include="$(SolutionDir)NopCommerce\src\Libraries\Nop.Data\Nop.Data.csproj" />
    <ProjectReference Include="$(SolutionDir)NopCommerce\src\Libraries\Nop.Services\Nop.Services.csproj" />
    <ProjectReference Include="$(SolutionDir)NopCommerce\src\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="logo.jpg" />
    <Content Include="logo.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="plugin.json" />
    <Content Include="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="countries.json" />
    <Content Include="countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <Target Name="FilterCopyLocalItems" AfterTargets="ResolveLockFileCopyLocalProjectDeps">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' != 'Microsoft.AspNetCore.Rewrite' AND '%(Filename)' != 'System.IdentityModel.Tokens.Jwt'" />
    </ItemGroup>
  </Target>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
  </Target>
</Project>
