name: Build and Deploy .NET 9.0
run-name: Build and Deploy .NET 9.0

on:
  pull_request:
    branches: ["develop"]
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      build:
        description: "Build and deploy"
        required: true
        default: "true"

jobs:
  build_and_deploy:
    runs-on: windows-latest
    env:
      PUBLISH_OUTPUT_PATH: C:\tmp\kivio_ecommerce_binaries
      PUBLISH_ZIP_NAME: binaries.zip
    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configurar el agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KIVIO_ECOMMERCE_BASE_SECRET_KEY }}

      - name: Verificar llaves cargadas en el agente SSH
        run: ssh-add -l

      - name: Probar conexión SSH
        run: ssh -v -o StrictHostKeyChecking=no ${{ secrets.KIVIO_ECOMMERCE_BASE_USER }}@${{ secrets.KIVIO_ECOMMERCE_BASE_HOST }} "echo 'Conexión exitosa'"

      - name: Switch to develop branch
        run: |
          git fetch origin
          git checkout develop
          git pull origin develop

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Init Scripts
        run: powershell -ExecutionPolicy Bypass -File .\init.ps1

      - name: Remove BeforeBuild from sln
        run: dotnet sln remove .\BeforeBuild\BeforeBuild.csproj

      - name: Restore
        run: dotnet restore KivioEcommerce.sln

      - name: Build
        run: dotnet build KivioEcommerce.sln --no-restore

      - name: Publish
        env:
          PUBLISH_PROJECT_PATH: ${{ vars.KIVIO_ECOMMERCE_PUBLISH_PROJECT_PATH_BASE }}
        run: dotnet publish "${{ vars.KIVIO_ECOMMERCE_PUBLISH_PROJECT_PATH_BASE }}" -c Release -o "${{ env.PUBLISH_OUTPUT_PATH }}"

      - name: Comprimir binarios
        run: powershell Compress-Archive -Path "${{ env.PUBLISH_OUTPUT_PATH }}\*" -DestinationPath ${{ env.PUBLISH_ZIP_NAME }}

      - name: Verificar existencia del zip
        run: dir

     
      - name: Transferir ZIP al servidor remoto usando SCP
        env:
          SSH_USER: ${{ secrets.KIVIO_ECOMMERCE_BASE_USER }}
          EC2_HOST: ${{ secrets.KIVIO_ECOMMERCE_BASE_HOST }}
          BINARIES_PATH: ${{ vars.KIVIO_ECOMMERCE_BINARIES_PATH_BASE }}
        run: scp -o StrictHostKeyChecking=no ${{ env.PUBLISH_ZIP_NAME }} ${{ secrets.KIVIO_ECOMMERCE_BASE_USER }}@${{ secrets.KIVIO_ECOMMERCE_BASE_HOST }}:${{ vars.KIVIO_ECOMMERCE_BINARIES_PATH_BASE }}/${{ env.PUBLISH_ZIP_NAME }}
