name: Build and Deploy .NET 9.0
run-name: Build and Deploy .NET 9.0

on:
  pull_request:
    branches: ["develop"]
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      build:
        description: "Build and deploy"
        required: true
        default: "true"

jobs:
  build_on_windows:
    runs-on: windows-latest
    env:
      PUBLISH_OUTPUT_PATH: C:\tmp\kivio_ecommerce_binaries
    steps:
      - name: Check out repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true  
          fetch-depth: 0

      - name: Debug - List directories
        run: tree

      - name: Switch to develop branch
        run: |
          git fetch origin
          git checkout develop
          git pull origin develop

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Init Scripts
        run: powershell -ExecutionPolicy Bypass -File .\init.ps1

      - name: Remove BeforeBuild from sln
        run:  dotnet sln remove .\BeforeBuild\BeforeBuild.csproj

      - name: Restore
        run: dotnet restore KivioEcommerce.sln

      - name: Build
        run: dotnet build KivioEcommerce.sln --no-restore

      - name: Publish
        env:
          PUBLISH_PROJECT_PATH: C:\tmp\kivio_ecommerce_binaries
        run: |
          dotnet publish "$PUBLISH_PROJECT_PATH" -c Release -o "C:\tmp\kivio_ecommerce_binaries"

      - name: Comprimir binarios
        run: powershell Compress-Archive -Path "C:\tmp\kivio_ecommerce_binaries\*" -DestinationPath binaries.zip

      - name: Cargar artefactos para siguientes jobs
        uses: actions/upload-artifact@v3
        with:
          name: publish_output
          path: binaries.zip

  deploy_linux:
    runs-on: ubuntu-latest
    needs: build_on_windows
    env:
      PUBLISH_OUTPUT_PATH: /tmp/kivio_ecommerce_binaries
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v3
        with:
          name: publish_output
          path: ./binaries

      - name: Extraer binarios
        run: |
          unzip binaries.zip -d /tmp/kivio_ecommerce_binaries

      - name: Configurar el agente SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KIVIO_ECOMMERCE_BASE_SECRET_KEY }}

      - name: Transferir binarios a servidor remoto (rsync)
        env:
          SSH_USER: ${{ secrets.KIVIO_ECOMMERCE_BASE_USER }}
          EC2_HOST: ${{ secrets.KIVIO_ECOMMERCE_BASE_HOST }}
          BINARIES_PATH: ${{ vars.KIVIO_ECOMMERCE_BINARIES_PATH_BASE }}
        run: |
          rsync -avz --progress \
            -e "ssh -o StrictHostKeyChecking=no" \
            "$PUBLISH_OUTPUT_PATH/" \
            "$SSH_USER@$EC2_HOST:$BINARIES_PATH"
